source 'https://rubygems.org'

gem 'bundler', '1.17.3'
gem 'rails', '4.2.11'
gem 'sqlite3', '~> 1.3.6'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby
gem 'byebug'

gem 'jquery-rails'
gem 'turbolinks'

gem 'devise'
gem 'devise-two-factor', path: '../'
gem 'rqrcode'
