source 'https://rubygems.org'

gem 'rails', '~> 6.1.7.2'
gem 'sqlite3'
gem 'sassc-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks'

gem 'devise'
gem 'devise-two-factor', path: '../'
gem 'rqrcode-rails3'
