source 'https://rubygems.org'

gem 'rails', '4.2.7.1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks'

gem 'devise'
gem 'devise-two-factor', path: '../'
gem 'rqrcode-rails3'
