name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Due to https://github.com/actions/runner/issues/849, we should quote versions
        ruby: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', 'truffleruby-head']
        rails: ['4.1', '4.2', '5.0', '5.1', '5.2', '6.0', '6.1', '7.0']
        exclude:
          - { ruby: '2.3', rails: '7.0' }
          - { ruby: '2.4', rails: '7.0' }
          - { ruby: '2.5', rails: '7.0' }
          - { ruby: '2.6', rails: '7.0' }
          - { ruby: '2.3', rails: '6.0' }
          - { ruby: '2.3', rails: '6.1' }
          - { ruby: '2.4', rails: '6.0' }
          - { ruby: '2.4', rails: '6.1' }
          - { ruby: '2.7', rails: '4.1' }
          - { ruby: '2.7', rails: '4.2' }
          - { ruby: '3.0', rails: '4.1' }
          - { ruby: '3.0', rails: '4.2' }
          - { ruby: 'truffleruby-head', rails: '4.1' }
          - { ruby: 'truffleruby-head', rails: '4.2' }

    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Print versions
        continue-on-error: true
        run: |
          ruby --version
          bundle --version
          echo "RubyGems version `gem --version`"
          bundle exec rails --version
      - name: Run tests
        run: bundle exec rake
